export const ActionTypes = {
    SET_PRODUCTS: "SET_PRODUCTS",
    SELECTED_PRODUCT: "SELECTED_PRODUCT",
    FILTER_PRODUCTS_BY_SIZE: "FILTER_PRODUCTS_BY_SIZE",
    REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
    ADD_TO_CART: "ADD_TO_CART",
}